services:
  vitrine:
    image: nginx:alpine
    container_name: vitrine_solutionnumerique
    restart: unless-stopped
    volumes:
      - ./solutionnumerique:/usr/share/nginx/html:ro
    networks:
      - webnet

networks:
  webnet:
    external: true